version: '3'

services:
 registry:
  image: registry:2
#  ports:
#   - "5000:5000"
  environment:
   REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
   REGISTRY_AUTH: htpasswd
   REGISTRY_AUTH_HTPASSWD_REALM: Registry
   REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
  volumes:
   - ./data:/data
   - ./auth:/auth
  restart: always

 nginx:
  image: nginx:alpine
  volumes:
   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
   - ./nginx/key.pem:/root/ssl/key.pem:ro
   - ./nginx/cert.pem:/root/ssl/cert.pem:ro
  ports:
   - "443:443"
  depends_on:
   - registry
  restart: always
